language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t daavo03/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daavo03/docker-react npm run test